@url = http://localhost:3000

GET {{url}}/employees/
###

GET {{url}}/employees/d2a83616c5f6eab1da92
###

POST {{url}}/employees/
Content-Type: application/json

{
    "name": "John",
    "position": "Manager",
    "salary":50000
}